version: "3.0"

services:
  ftx-bot:
    container_name: ftx-bot
    depends_on:
      - ftx-db
    build:
      context: ../
      dockerfile: docker/Dockerfile
    image: ftx-bot:latest
    hostname: ftx-bot
    ports:
      - "80:80"
    restart: always
  ftx-db:
    container_name: ftx-db
    image: postgres:13.3
    volumes:
      - ./dbData:/var/lib/postgresql/data
      - ./init-database.sh:/docker-entrypoint-initdb.d/init-database.sh
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
      DB_NAME: "${DB_NAME}"
      PGDATA: /var/lib/postgresql/data/pgdata
    restart: always